add_newline = false
# A minimal left prompt
format = ***REMOVED******REMOVED******REMOVED***$directory$character***REMOVED******REMOVED******REMOVED***
palette = ***REMOVED***catppuccin_mocha***REMOVED***
# move the rest of the prompt to the right
right_format = ***REMOVED******REMOVED******REMOVED***$all***REMOVED******REMOVED******REMOVED***
command_timeout = 1000

[character]
vicmd_symbol = ***REMOVED***[N] >>>***REMOVED***
success_symbol = '[➜](bold green)'

[directory.substitutions]
'~/tests/starship-custom' = 'work-project'

[git_branch]
format =  '[$symbol$branch(:$remote_branch)]($style)'

[aws]
format = '[$symbol(pro***REMOVED***le: ***REMOVED***$pro***REMOVED***le***REMOVED*** )(\(region: $region\) )]($style)'
disabled = false
style = 'bold blue'
symbol = ***REMOVED*** ***REMOVED***

[golang]
format = '[ ](bold cyan)'

[kubernetes]
symbol = '☸ '
disabled = true
detect_***REMOVED***les = ['Docker***REMOVED***le']
format = '[$symbol$context( \($namespace\))]($style) '
contexts = [
  { context_pattern = ***REMOVED***arn:aws:eks:us-west-2:577926974532:cluster/zd-pvc-omer***REMOVED***, style = ***REMOVED***green***REMOVED***, context_alias = ***REMOVED***omerxx***REMOVED***, symbol = ***REMOVED*** ***REMOVED*** },
]

[docker_context]
disabled = true

[palettes.catppuccin_mocha]
rosewater = ***REMOVED***#f5e0dc***REMOVED***
flamingo = ***REMOVED***#f2cdcd***REMOVED***
pink = ***REMOVED***#f5c2e7***REMOVED***
mauve = ***REMOVED***#cba6f7***REMOVED***
red = ***REMOVED***#f38ba8***REMOVED***
maroon = ***REMOVED***#eba0ac***REMOVED***
peach = ***REMOVED***#fab387***REMOVED***
yellow = ***REMOVED***#f9e2af***REMOVED***
green = ***REMOVED***#a6e3a1***REMOVED***
teal = ***REMOVED***#94e2d5***REMOVED***
sky = ***REMOVED***#89dceb***REMOVED***
sapphire = ***REMOVED***#74c7ec***REMOVED***
blue = ***REMOVED***#89b4fa***REMOVED***
lavender = ***REMOVED***#b4befe***REMOVED***
text = ***REMOVED***#cdd6f4***REMOVED***
subtext1 = ***REMOVED***#bac2de***REMOVED***
subtext0 = ***REMOVED***#a6adc8***REMOVED***
overlay2 = ***REMOVED***#9399b2***REMOVED***
overlay1 = ***REMOVED***#7f849c***REMOVED***
overlay0 = ***REMOVED***#6c7086***REMOVED***
surface2 = ***REMOVED***#585b70***REMOVED***
surface1 = ***REMOVED***#45475a***REMOVED***
surface0 = ***REMOVED***#313244***REMOVED***
base = ***REMOVED***#1e1e2e***REMOVED***
mantle = ***REMOVED***#181825***REMOVED***
crust = ***REMOVED***#11111b***REMOVED***
