format = ***REMOVED******REMOVED******REMOVED***
$username\
$hostname\
$directory\
$git_branch\
$golang\
$git_state\
$git_status\
$git_metrics\
$aws\
$***REMOVED***ll\
${custom.package_manager}\
$nodejs\
$rust\
$python\
${custom.home} $cmd_duration $jobs $time\
$line_break\
$character***REMOVED******REMOVED******REMOVED***

[aws]
format = '[$symbol(pro***REMOVED***le: ***REMOVED***$pro***REMOVED***le***REMOVED*** )(\(region: $region\) )]($style)'
disabled = false
style = 'bold blue'
symbol = ***REMOVED*** ***REMOVED***

[python]
symbol = ***REMOVED*** ***REMOVED***
style = ***REMOVED***bold yellow***REMOVED***
format = ***REMOVED***[$symbol$virtualenv]($style) ***REMOVED***

[rust]
format = ***REMOVED***[$symbol($version )]($style)***REMOVED***
symbol = ***REMOVED*** rust***REMOVED***
style = ***REMOVED***bold red***REMOVED***

[nodejs]
format = ***REMOVED***[$symbol($version )]($style)***REMOVED***
detect_***REMOVED***les = [***REMOVED***package.json***REMOVED***, ***REMOVED***node_modules***REMOVED***]
detect_folders = [***REMOVED***node_modules***REMOVED***]

[custom.package_manager]
command = ***REMOVED******REMOVED******REMOVED***
if [ -f package-lock.json ]; then
    echo ***REMOVED***npm***REMOVED***
elif [ -f yarn.lock ]; then
    echo ***REMOVED***yarn***REMOVED***
elif [ -f pnpm-lock.yaml ]; then
    echo ***REMOVED***pnpm***REMOVED***
elif [ -f bun.lockb ]; then
    echo ***REMOVED***bun***REMOVED***
***REMOVED***
    exit 1
***REMOVED***
***REMOVED******REMOVED******REMOVED***
when = ***REMOVED******REMOVED******REMOVED***test -f package.json || test -f yarn.lock || test -f pnpm-lock.yaml || test -f bun.lockb***REMOVED******REMOVED******REMOVED***
style = ***REMOVED***bold yellow***REMOVED***
format = ***REMOVED***[$output ]($style)***REMOVED***

[***REMOVED***ll]
symbol = ***REMOVED*** ***REMOVED***

[directory]
style = ***REMOVED***blue***REMOVED***
read_only = ***REMOVED*** ***REMOVED***
truncation_length = 4
truncate_to_repo = false

[character]
success_symbol = ***REMOVED***[❯](purple)***REMOVED***
error_symbol = ***REMOVED***[❯](red)***REMOVED***
vicmd_symbol = ***REMOVED***[❮](green)***REMOVED***

[git_branch]
symbol = ***REMOVED*** ***REMOVED***
format = ***REMOVED***[$symbol$branch]($style) ***REMOVED***
style = ***REMOVED***green***REMOVED***

[jobs]
symbol = ***REMOVED***  ***REMOVED***
style = ***REMOVED***bold red***REMOVED***
number_threshold = 1
format = ***REMOVED***[$symbol]($style)***REMOVED***

[golang]
format = '[ ](bold cyan)'

[git_status]
format = '([\[$all_status$ahead_behind\]]($style) )'
style = ***REMOVED***cyan***REMOVED***

[git_state]
format = '\([$state( $progress_current/$progress_total)]($style)\) '
style = ***REMOVED***bright-black***REMOVED***

[git_metrics]
disabled = false

[cmd_duration]
format = ***REMOVED***[$duration]($style)***REMOVED***
style = ***REMOVED***yellow***REMOVED***

[memory_usage]
symbol = ***REMOVED*** ***REMOVED***

[time]
disabled = false
style = ***REMOVED***bold white***REMOVED***
format = ***REMOVED***[$time]($style)***REMOVED***

[custom.home]
when = ***REMOVED***test $HOME = $PWD***REMOVED***
format = ***REMOVED***🏠***REMOVED***

