format = """
$username\
$hostname\
$directory\
$git_branch\
$golang\
$git_state\
$git_status\
$git_metrics\
$aws\
$fill\
${custom.package_manager}\
$nodejs\
$rust\
$python\
${custom.home} $cmd_duration $jobs $time\
$line_break\
$character"""

[aws]
format = '[$symbol(profile: "$profile" )(\(region: $region\) )]($style)'
disabled = false
style = 'bold blue'
symbol = " "

[python]
symbol = " "
style = "bold yellow"
format = "[$symbol$virtualenv]($style) "

[rust]
format = "[$symbol($version )]($style)"
symbol = " rust"
style = "bold red"

[nodejs]
format = "[$symbol($version )]($style)"
detect_files = ["package.json", "node_modules"]
detect_folders = ["node_modules"]

[custom.package_manager]
command = """
if [ -f package-lock.json ]; then
    echo "npm"
elif [ -f yarn.lock ]; then
    echo "yarn"
elif [ -f pnpm-lock.yaml ]; then
    echo "pnpm"
elif [ -f bun.lockb ]; then
    echo "bun"
else
    exit 1
fi
"""
when = """test -f package.json || test -f yarn.lock || test -f pnpm-lock.yaml || test -f bun.lockb"""
style = "bold yellow"
format = "[$output ]($style)"

[fill]
symbol = " "

[directory]
style = "blue"
read_only = "🔒 "
truncation_length = 4
truncate_to_repo = false

[character]
success_symbol = "[❯](purple)"
error_symbol = "[❯](red)"
vicmd_symbol = "[❮](green)"

[git_branch]
symbol = " "
format = "[$symbol$branch]($style) "
style = "green"

[jobs]
symbol = "  "
style = "bold red"
number_threshold = 1
format = "[$symbol]($style)"

[golang]
format = '[ ](bold cyan)'

[git_status]
format = '([\[$all_status$ahead_behind\]]($style) )'
style = "cyan"

[git_state]
format = '\([$state( $progress_current/$progress_total)]($style)\) '
style = "bright-black"

[git_metrics]
disabled = false

[cmd_duration]
format = "[$duration]($style)"
style = "yellow"

[memory_usage]
symbol = " "

[time]
disabled = false
style = "bold white"
format = "[$time]($style)"

[custom.home]
when = "test $HOME = $PWD"
format = "🏠"
