require(***REMOVED***crates***REMOVED***).setup({
	smart_insert = true,
	insert_closing_quote = true,
	autoload = true,
	autoupdate = true,
	autoupdate_throttle = 250,
	loading_indicator = true,
	search_indicator = true,
	date_format = ***REMOVED***%Y-%m-%d***REMOVED***,
	thousands_separator = ***REMOVED***.***REMOVED***,
	noti***REMOVED***cation_title = ***REMOVED***crates.nvim***REMOVED***,
	curl_args = { ***REMOVED***-sL***REMOVED***, ***REMOVED***--retry***REMOVED***, ***REMOVED***1***REMOVED*** },
	max_parallel_requests = 80,
	expand_crate_moves_cursor = true,
	enable_update_available_warning = true,
	on_attach = function(bufnr) end,
	text = {
		searching = ***REMOVED***   Searching***REMOVED***,
		loading = ***REMOVED***   Loading***REMOVED***,
		version = ***REMOVED***   %s***REMOVED***,
		prerelease = ***REMOVED***   %s***REMOVED***,
		yanked = ***REMOVED***   %s***REMOVED***,
		nomatch = ***REMOVED***   No match***REMOVED***,
		upgrade = ***REMOVED***   %s***REMOVED***,
		error = ***REMOVED***   Error fetching crate***REMOVED***,
	},
	highlight = {
		searching = ***REMOVED***CratesNvimSearching***REMOVED***,
		loading = ***REMOVED***CratesNvimLoading***REMOVED***,
		version = ***REMOVED***CratesNvimVersion***REMOVED***,
		prerelease = ***REMOVED***CratesNvimPreRelease***REMOVED***,
		yanked = ***REMOVED***CratesNvimYanked***REMOVED***,
		nomatch = ***REMOVED***CratesNvimNoMatch***REMOVED***,
		upgrade = ***REMOVED***CratesNvimUpgrade***REMOVED***,
		error = ***REMOVED***CratesNvimError***REMOVED***,
	},
	popup = {
		autofocus = false,
		hide_on_select = false,
		copy_register = '***REMOVED***',
		style = ***REMOVED***minimal***REMOVED***,
		border = ***REMOVED***none***REMOVED***,
		show_version_date = false,
		show_dependency_version = true,
		max_height = 30,
		min_width = 20,
		padding = 1,
		text = {
			title = ***REMOVED*** %s***REMOVED***,
			pill_left = ***REMOVED******REMOVED***,
			pill_right = ***REMOVED******REMOVED***,
			description = ***REMOVED***%s***REMOVED***,
			created_label = ***REMOVED*** created        ***REMOVED***,
			created = ***REMOVED***%s***REMOVED***,
			updated_label = ***REMOVED*** updated        ***REMOVED***,
			updated = ***REMOVED***%s***REMOVED***,
			downloads_label = ***REMOVED*** downloads      ***REMOVED***,
			downloads = ***REMOVED***%s***REMOVED***,
			homepage_label = ***REMOVED*** homepage       ***REMOVED***,
			homepage = ***REMOVED***%s***REMOVED***,
			repository_label = ***REMOVED*** repository     ***REMOVED***,
			repository = ***REMOVED***%s***REMOVED***,
			documentation_label = ***REMOVED*** documentation  ***REMOVED***,
			documentation = ***REMOVED***%s***REMOVED***,
			crates_io_label = ***REMOVED*** crates.io      ***REMOVED***,
			crates_io = ***REMOVED***%s***REMOVED***,
			lib_rs_label = ***REMOVED*** lib.rs         ***REMOVED***,
			lib_rs = ***REMOVED***%s***REMOVED***,
			categories_label = ***REMOVED*** categories     ***REMOVED***,
			keywords_label = ***REMOVED*** keywords       ***REMOVED***,
			version = ***REMOVED***  %s***REMOVED***,
			prerelease = ***REMOVED*** %s***REMOVED***,
			yanked = ***REMOVED*** %s***REMOVED***,
			version_date = ***REMOVED***  %s***REMOVED***,
			feature = ***REMOVED***  %s***REMOVED***,
			enabled = ***REMOVED*** %s***REMOVED***,
			transitive = ***REMOVED*** %s***REMOVED***,
			normal_dependencies_title = ***REMOVED*** Dependencies***REMOVED***,
			build_dependencies_title = ***REMOVED*** Build dependencies***REMOVED***,
			dev_dependencies_title = ***REMOVED*** Dev dependencies***REMOVED***,
			dependency = ***REMOVED***  %s***REMOVED***,
			optional = ***REMOVED*** %s***REMOVED***,
			dependency_version = ***REMOVED***  %s***REMOVED***,
			loading = ***REMOVED***  ***REMOVED***,
		},
		highlight = {
			title = ***REMOVED***CratesNvimPopupTitle***REMOVED***,
			pill_text = ***REMOVED***CratesNvimPopupPillText***REMOVED***,
			pill_border = ***REMOVED***CratesNvimPopupPillBorder***REMOVED***,
			description = ***REMOVED***CratesNvimPopupDescription***REMOVED***,
			created_label = ***REMOVED***CratesNvimPopupLabel***REMOVED***,
			created = ***REMOVED***CratesNvimPopupValue***REMOVED***,
			updated_label = ***REMOVED***CratesNvimPopupLabel***REMOVED***,
			updated = ***REMOVED***CratesNvimPopupValue***REMOVED***,
			downloads_label = ***REMOVED***CratesNvimPopupLabel***REMOVED***,
			downloads = ***REMOVED***CratesNvimPopupValue***REMOVED***,
			homepage_label = ***REMOVED***CratesNvimPopupLabel***REMOVED***,
			homepage = ***REMOVED***CratesNvimPopupUrl***REMOVED***,
			repository_label = ***REMOVED***CratesNvimPopupLabel***REMOVED***,
			repository = ***REMOVED***CratesNvimPopupUrl***REMOVED***,
			documentation_label = ***REMOVED***CratesNvimPopupLabel***REMOVED***,
			documentation = ***REMOVED***CratesNvimPopupUrl***REMOVED***,
			crates_io_label = ***REMOVED***CratesNvimPopupLabel***REMOVED***,
			crates_io = ***REMOVED***CratesNvimPopupUrl***REMOVED***,
			lib_rs_label = ***REMOVED***CratesNvimPopupLabel***REMOVED***,
			lib_rs = ***REMOVED***CratesNvimPopupUrl***REMOVED***,
			categories_label = ***REMOVED***CratesNvimPopupLabel***REMOVED***,
			keywords_label = ***REMOVED***CratesNvimPopupLabel***REMOVED***,
			version = ***REMOVED***CratesNvimPopupVersion***REMOVED***,
			prerelease = ***REMOVED***CratesNvimPopupPreRelease***REMOVED***,
			yanked = ***REMOVED***CratesNvimPopupYanked***REMOVED***,
			version_date = ***REMOVED***CratesNvimPopupVersionDate***REMOVED***,
			feature = ***REMOVED***CratesNvimPopupFeature***REMOVED***,
			enabled = ***REMOVED***CratesNvimPopupEnabled***REMOVED***,
			transitive = ***REMOVED***CratesNvimPopupTransitive***REMOVED***,
			normal_dependencies_title = ***REMOVED***CratesNvimPopupNormalDependenciesTitle***REMOVED***,
			build_dependencies_title = ***REMOVED***CratesNvimPopupBuildDependenciesTitle***REMOVED***,
			dev_dependencies_title = ***REMOVED***CratesNvimPopupDevDependenciesTitle***REMOVED***,
			dependency = ***REMOVED***CratesNvimPopupDependency***REMOVED***,
			optional = ***REMOVED***CratesNvimPopupOptional***REMOVED***,
			dependency_version = ***REMOVED***CratesNvimPopupDependencyVersion***REMOVED***,
			loading = ***REMOVED***CratesNvimPopupLoading***REMOVED***,
		},
		keys = {
			hide = { ***REMOVED***q***REMOVED***, ***REMOVED***<esc>***REMOVED*** },
			open_url = { ***REMOVED***<cr>***REMOVED*** },
			select = { ***REMOVED***<cr>***REMOVED*** },
			select_alt = { ***REMOVED***s***REMOVED*** },
			toggle_feature = { ***REMOVED***<cr>***REMOVED*** },
			copy_value = { ***REMOVED***yy***REMOVED*** },
			goto_item = { ***REMOVED***gd***REMOVED***, ***REMOVED***K***REMOVED***, ***REMOVED***<C-LeftMouse>***REMOVED*** },
			jump_forward = { ***REMOVED***<c-i>***REMOVED*** },
			jump_back = { ***REMOVED***<c-o>***REMOVED***, ***REMOVED***<C-RightMouse>***REMOVED*** },
		},
	},
	completion = {
		insert_closing_quote = true,
		text = {
			prerelease = ***REMOVED***  pre-release ***REMOVED***,
			yanked = ***REMOVED***  yanked ***REMOVED***,
		},
		cmp = {
			enabled = true,
			use_custom_kind = true,
			kind_text = {
				version = ***REMOVED***Version***REMOVED***,
				feature = ***REMOVED***Feature***REMOVED***,
			},
			kind_highlight = {
				version = ***REMOVED***CmpItemKindVersion***REMOVED***,
				feature = ***REMOVED***CmpItemKindFeature***REMOVED***,
			},
		},
		coq = {
			enabled = false,
			name = ***REMOVED***crates.nvim***REMOVED***,
		},
		crates = {
			enabled = false,
			min_chars = 3,
			max_results = 8,
		},
	},
	null_ls = {
		enabled = false,
		name = ***REMOVED***crates.nvim***REMOVED***,
	},
	neoconf = {
		enabled = false,
		namespace = ***REMOVED***crates***REMOVED***,
	},
	lsp = {
		enabled = true,
		name = ***REMOVED***crates.nvim***REMOVED***,
		on_attach = function(client, bufnr) end,
		actions = true,
		completion = true,
		hover = true,
	},
})
