local trouble = require(***REMOVED***trouble***REMOVED***)
trouble.setup({
	opts = {
		position = ***REMOVED***bottom***REMOVED***,
		height = 10,
		width = 50,
		icons = true,
		mode = ***REMOVED***workspace_diagnostics***REMOVED***,
		severity = nil,
		fold_open = ***REMOVED******REMOVED***,
		fold_closed = ***REMOVED******REMOVED***,
		group = true,
		padding = true,
		cycle_results = true,
		action_keys = {
			close = ***REMOVED***q***REMOVED***,
			cancel = ***REMOVED***<esc>***REMOVED***,
			refresh = ***REMOVED***r***REMOVED***,
			jump = { ***REMOVED***<cr>***REMOVED***, ***REMOVED***<tab>***REMOVED***, ***REMOVED***<2-leftmouse>***REMOVED*** },
			open_split = { ***REMOVED***<c-x>***REMOVED*** },
			open_vsplit = { ***REMOVED***<c-v>***REMOVED*** },
			open_tab = { ***REMOVED***<c-t>***REMOVED*** },
			jump_close = { ***REMOVED***o***REMOVED*** },
			toggle_mode = ***REMOVED***m***REMOVED***,
			switch_severity = ***REMOVED***s***REMOVED***,
			toggle_preview = ***REMOVED***P***REMOVED***,
			hover = ***REMOVED***K***REMOVED***,
			preview = ***REMOVED***p***REMOVED***,
			open_code_href = ***REMOVED***c***REMOVED***,
			close_folds = { ***REMOVED***zM***REMOVED***, ***REMOVED***zm***REMOVED*** },
			open_folds = { ***REMOVED***zR***REMOVED***, ***REMOVED***zr***REMOVED*** },
			toggle_fold = { ***REMOVED***zA***REMOVED***, ***REMOVED***za***REMOVED*** },
			previous = ***REMOVED***k***REMOVED***,
			next = ***REMOVED***j***REMOVED***,
			help = ***REMOVED***?***REMOVED***,
		},
		multiline = true,
		indent_lines = true,
		win_con***REMOVED***g = { border = ***REMOVED***single***REMOVED*** },
		auto_open = false,
		auto_close = false,
		auto_preview = true,
		auto_fold = false,
		auto_jump = { ***REMOVED***lsp_de***REMOVED***nitions***REMOVED*** },
		include_declaration = { ***REMOVED***lsp_references***REMOVED***, ***REMOVED***lsp_implementations***REMOVED***, ***REMOVED***lsp_de***REMOVED***nitions***REMOVED*** },
		signs = {
			error = ***REMOVED******REMOVED***,
			warning = ***REMOVED******REMOVED***,
			hint = ***REMOVED******REMOVED***,
			information = ***REMOVED******REMOVED***,
			other = ***REMOVED******REMOVED***,
		},
		use_diagnostic_signs = false,
	},
})
